FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . .
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENV GRAPH_API_TOKEN="EAAHHeZBqAlvEBO9KeR75Ly1k9dGu9WZBPAV3tKZAbW4ZBDPSIaMTZBIkAMhOdJdu6DHFO9AZA69Trv1hez3y7nIJCUqtb0oc3SGsaJtpO6fhtOquCFOERmH9ZC7Sodu16yT5Sdi7m2sLgHZBdnhbrU8Kaz68HJX6kUYZAjjXfxt6zD6cZBGFOUiwF8zUvZCYUAHa7HrAQZDZD"
ENV WEBHOOK_VERIFY_TOKEN="HAPPY"

ENTRYPOINT ["/entrypoint.sh"]

CMD ["python3", "helpdeskWorker.py"]
